/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  // Built from the directory tree. Order comes from _category_.json (parts)
  // and sidebar_position in each section's frontmatter.
  manualSidebar: [{ type: 'autogenerated', dirName: '.' }],
};
